"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { startTransition, useEffect, useRef, useState } from "react";
import {
  ArrowDownToLine,
  ArrowLeftRight,
  BarChart3,
  BadgeCheck,
  BriefcaseBusiness,
  CircleHelp,
  Eye,
  EyeOff,
  History,
  Home,
  LayoutDashboard,
  LogOut,
  Menu,
  Moon,
  Receipt,
  Settings,
  Sun,
  UserRound,
  UsersRound,
  Wallet,
} from "lucide-react";
import StatCard from "@/components/StatCard";
import { useLanguage } from "@/components/LanguageProvider";
import DashboardSupport from "@/components/DashboardSupport";
import DashboardInvestmentPlans from "@/components/DashboardInvestmentPlans";
import DashboardWithdraw from "@/components/DashboardWithdraw";
import DashboardDeposit from "@/components/DashboardDeposit";
import DashboardSwapCrypto from "@/components/DashboardSwapCrypto";
import DashboardReferrals from "@/components/DashboardReferrals";
import DashboardTransactions from "@/components/DashboardTransactions";
import DashboardManagedAccount from "@/components/DashboardManagedAccount";
import DashboardProfitHistory from "@/components/DashboardProfitHistory";
import DashboardProfile from "@/components/DashboardProfile";
import DashboardKyc from "@/components/DashboardKyc";
import DashboardActivePositions from "@/components/DashboardActivePositions";
import { clearAuthSession, useAuthSession } from "@/hooks/useAuthSession";

const nav = [
  [LayoutDashboard, "Overview"],
  [BriefcaseBusiness, "My investments"],
  [Receipt, "Transactions"],
  [ArrowLeftRight, "Swap crypto"],
  [BriefcaseBusiness, "Managed account"],
  [Wallet, "Deposit"],
  [ArrowDownToLine, "Withdraw"],
  [BadgeCheck, "KYC verification"],
  [BarChart3, "Investment plans"],
  [History, "Profit history"],
  [UserRound, "Profile"],
  [UsersRound, "Referrals"],
  [CircleHelp, "Support"],
];

const sectionContent = {
  "My investments": ["Active positions", "3 active investments", "Review allocation and current investment performance."],
  Transactions: ["Transaction history", "24 completed transactions", "Review deposits, withdrawals, and investment activity."],
  "Swap crypto": ["Swap crypto", "Trade supported assets", "Choose the assets and amount you want to exchange."],
  "Managed account": ["Managed account", "Account management", "Review your managed account status and assigned strategy."],
  Deposit: ["Deposit funds", "Add funds to your account", "Choose a supported asset and follow the deposit instructions."],
  Withdraw: ["Withdraw funds", "Move funds securely", "Choose a destination and submit a withdrawal request."],
  "Investment plans": ["Investment plans", "Choose a strategy", "Compare available plans and select the one that fits your goals."],
  "Profit history": ["Profit history", "Performance over time", "Review profits generated by your investments."],
  Profile: ["Profile", "Personal information", "Manage your account details and verification status."],
  "KYC verification": ["Identity verification", "Complete account verification", "Verify your identity to help us protect your account."],
  Referrals: ["Referrals", "Invite and earn", "Track your referral activity and rewards."],
  Support: ["Support", "How can we help?", "Contact the RiverTrade support team for assistance."],
};

function DashboardSection({ section }) {
  if (section === "KYC verification") return <DashboardKyc />;
  if (section === "Support") return <DashboardSupport />;
  if (section === "Investment plans") return <DashboardInvestmentPlans />;
  if (section === "Withdraw") return <DashboardWithdraw />;
  if (section === "Deposit") return <DashboardDeposit />;
  if (section === "Swap crypto") return <DashboardSwapCrypto />;
  if (section === "Referrals") return <DashboardReferrals />;
  if (section === "Transactions") return <DashboardTransactions />;
  if (section === "My investments") return <DashboardActivePositions />;
  if (section === "Managed account") return <DashboardManagedAccount />;
  if (section === "Profit history") return <DashboardProfitHistory />;
  if (section === "Profile") return <DashboardProfile />;

  const [title, metric, description] = sectionContent[section] || [section, "Dashboard section", "Manage this area of your RiverTrade account."];

  return (
    <section className="dashboard-section-view" aria-labelledby="dashboard-section-title">
      <div className="dashboard-section-view-head">
        <div>
          <p className="eyebrow">RiverTrade account</p>
          <h2 id="dashboard-section-title">{title}</h2>
          <p>{description}</p>
        </div>
        <button className="button" type="button">Get started</button>
      </div>
      <div className="dashboard-section-view-card">
        <span>Status</span>
        <strong>{metric}</strong>
        <small>Your account data will appear here as activity is recorded.</small>
      </div>
    </section>
  );
}

function TradingViewTicker({ theme }) {
  const containerRef = useRef(null);

  useEffect(() => {
    if (!containerRef.current) return undefined;
    const script = document.createElement("script");
    script.src = "https://s3.tradingview.com/external-embedding/embed-widget-ticker-tape.js";
    script.async = true;
    script.innerHTML = JSON.stringify({
      symbols: [
        { proName: "BINANCE:BTCUSDT", title: "Bitcoin" },
        { proName: "BINANCE:ETHUSDT", title: "Ethereum" },
        { proName: "BINANCE:BNBUSDT", title: "BNB" },
        { proName: "BINANCE:SOLUSDT", title: "Solana" },
        { proName: "BINANCE:XRPUSDT", title: "XRP" },
        { proName: "BINANCE:DOGEUSDT", title: "Dogecoin" },
      ],
      showSymbolLogo: true,
      colorTheme: theme,
      isTransparent: false,
      displayMode: "adaptive",
      locale: "en",
    });
    containerRef.current.appendChild(script);
    return () => {
      if (containerRef.current) containerRef.current.innerHTML = "";
    };
  }, [theme]);

  return (
    <section className="tradingview-ticker" aria-label="Live market ticker">
      <div className="tradingview-widget-container" ref={containerRef} />
    </section>
  );
}

const chartMarkets = [
  ["BTC", "BTC/USDT", "BINANCE:BTCUSDT"],
  ["ETH", "ETH/USDT", "BINANCE:ETHUSDT"],
  ["BNB", "BNB/USDT", "BINANCE:BNBUSDT"],
  ["SOL", "SOL/USDT", "BINANCE:SOLUSDT"],
  ["XRP", "XRP/USDT", "BINANCE:XRPUSDT"],
  ["DOGE", "DOGE/USDT", "BINANCE:DOGEUSDT"],
];

function TradingViewChart({ symbol, title, theme }) {
  const containerRef = useRef(null);

  useEffect(() => {
    if (!containerRef.current) return undefined;
    const script = document.createElement("script");
    script.src = "https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js";
    script.async = true;
    script.innerHTML = JSON.stringify({
      autosize: true,
      symbol,
      interval: "60",
      timezone: "Etc/UTC",
      theme,
      style: "1",
      locale: "en",
      allow_symbol_change: false,
      hide_top_toolbar: false,
      hide_legend: false,
      save_image: false,
      calendar: false,
      hide_volume: false,
      support_host: "https://www.tradingview.com",
    });
    containerRef.current.appendChild(script);
    return () => { if (containerRef.current) containerRef.current.innerHTML = ""; };
  }, [symbol, theme]);

  return (
    <article className="market-chart-card">
      <h3>{title}</h3>
      <div className="tradingview-chart" ref={containerRef} aria-label={`${title} TradingView chart`} />
    </article>
  );
}

function TradingViewMarketBoard({ theme }) {
  const [filter, setFilter] = useState("all");
  const visibleMarkets = filter === "all" ? chartMarkets : filter === "top" ? chartMarkets.slice(0, 3) : chartMarkets.filter(([code]) => code === filter);

  return (
    <section className="market-chart-board">
      <div className="market-chart-filter">
        <label htmlFor="chart-filter">Filter charts:</label>
        <select id="chart-filter" value={filter} onChange={(event) => setFilter(event.target.value)}>
          <option value="all">Show All</option>
          <option value="top">Top 3</option>
          {chartMarkets.map(([code]) => <option key={code} value={code}>{code}</option>)}
        </select>
      </div>
      <div className={`market-chart-grid ${visibleMarkets.length === 1 ? "single-chart" : ""}`}>
        {visibleMarkets.map(([code, title, symbol]) => <TradingViewChart key={code} title={title} symbol={symbol} theme={theme} />)}
      </div>
    </section>
  );
}

export default function DashboardPage() {
  const router = useRouter();
  const { language, setLanguage, t } = useLanguage();
  const { authenticated, user } = useAuthSession();
  const [visible, setVisible] = useState(true);
  const [sidebar, setSidebar] = useState(false);
  const [activeSection, setActiveSection] = useState("Overview");
  const [mobileMenuSection, setMobileMenuSection] = useState("");
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [currentDate, setCurrentDate] = useState("");
  const [greeting, setGreeting] = useState("");
  const [theme, setTheme] = useState(() => {
    if (typeof window === "undefined") return "light";
    const savedTheme = localStorage.getItem("rivertrade-dashboard-theme");
    return savedTheme === "dark" || savedTheme === "light" ? savedTheme : "light";
  });

  useEffect(() => {
    localStorage.setItem("rivertrade-dashboard-theme", theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  useEffect(() => {
    if (!authenticated) router.replace("/");
    else if (new URLSearchParams(window.location.search).get("kyc") === "required") {
      startTransition(() => setActiveSection("KYC verification"));
      router.replace("/dashboard");
    }
  }, [authenticated, router]);

  useEffect(() => {
    const updateDate = () => {
      const now = new Date();
      const localHour = Number(new Intl.DateTimeFormat(undefined, {
        hour: "numeric",
        hour12: false,
      }).format(now));
      setCurrentDate(new Intl.DateTimeFormat(undefined, {
        weekday: "long",
        month: "long",
        day: "numeric",
      }).format(now));

      setGreeting(localHour < 12 ? "Good morning" : localHour < 18 ? "Good afternoon" : "Good evening");
    };

    updateDate();
    const dateTimer = window.setInterval(updateDate, 30 * 1000);
    window.addEventListener("visibilitychange", updateDate);
    return () => {
      window.clearInterval(dateTimer);
      window.removeEventListener("visibilitychange", updateDate);
    };
  }, []);

  useEffect(() => {
    if (!sidebar || typeof window === "undefined") return undefined;

    window.history.pushState({ dashboardMenu: true }, "", window.location.href);
    const closeWithBack = () => setSidebar(false);
    window.addEventListener("popstate", closeWithBack);
    return () => window.removeEventListener("popstate", closeWithBack);
  }, [sidebar]);

  const logout = () => {
    clearAuthSession();
    router.push("/");
  };

  const openMobileSection = (section) => {
    setMobileMenuSection(section);
    setActiveSection(section);
    setSidebar(false);
  };

  const toggleMobileMenu = () => {
    if (sidebar) {
      window.history.back();
      return;
    }
    setSidebar(true);
  };

  if (!authenticated) return null;

  return (
    <div className={`dashboard ${theme === "dark" ? "theme-dark" : "theme-light"}`}>
      <aside className={sidebar ? "dashboard-side open" : "dashboard-side"}>
        <Link className="brand-mark dashboard-logo" href="/" aria-label="RiverTrade home">
          <img src="/icoinred/logo-88256519050c5e84fcbd2120a81b2097.svg" alt="RiverTrade" />
        </Link>
        <nav>
          {nav.map(([Icon, label]) => (
            <button className={activeSection === label ? "active" : ""} onClick={() => { setActiveSection(label); setMobileMenuSection(label); setSidebar(false); }} key={label}>
              <Icon size={17} />{label}
            </button>
          ))}
        </nav>
        <div className="side-foot">
          <small>Logged in as</small>
          <strong>{user?.firstName || user?.email || "Demo user"}</strong>
          <button onClick={logout}><LogOut size={15} /> Log out</button>
        </div>
      </aside>
      {sidebar && <button className="dashboard-drawer-backdrop" type="button" aria-label="Close dashboard menu" onClick={() => setSidebar(false)} />}

      <div className="dashboard-main">
        {!['Support', 'Investment plans', 'Withdraw', 'Deposit', 'Swap crypto', 'Referrals', 'Transactions', 'Managed account', 'Profit history', 'Profile', 'KYC verification', 'My investments'].includes(activeSection) && <header className="dash-header">
          <div>
            <p className="eyebrow">{currentDate}</p>
            <h1>{greeting}{user?.firstName ? `, ${user.firstName}` : ""}.</h1>
          </div>
          <div className="dash-actions">
            <button className="icon-button" aria-label="Toggle dark mode" onClick={() => setTheme((current) => (current === "dark" ? "light" : "dark"))}>
              {theme === "dark" ? <Sun size={17} /> : <Moon size={17} />}
            </button>
            <button className="icon-button" aria-label={t("settings")} aria-expanded={settingsOpen} onClick={() => setSettingsOpen((current) => !current)}>
              <Settings size={17} />
            </button>
            {settingsOpen && (
              <div className="dashboard-settings" role="dialog" aria-label={t("settings")}>
                <strong>{t("settings")}</strong>
                <label htmlFor="dashboard-language">{t("language")}</label>
                <select id="dashboard-language" value={language} onChange={(event) => setLanguage(event.target.value)}>
                  <option value="en">English</option>
                  <option value="es">Español</option>
                  <option value="fr">Français</option>
                  <option value="de">Deutsch</option>
                  <option value="pt">Português</option>
                  <option value="ja">日本語</option>
                  <option value="zh">中文</option>
                </select>
              </div>
            )}
          </div>
        </header>}

        {activeSection === "Overview" && <TradingViewTicker theme={theme} />}

        <main id="overview" className="dash-content">
          {activeSection !== "Overview" && <DashboardSection section={activeSection} />}
          {activeSection === "Overview" && <>
          <section className="balance-banner">
            <div>
              <span>Total portfolio value</span>
              <strong>{visible ? "$0.00" : "••••••••"}</strong>
              <small>No portfolio activity yet</small>
            </div>
            <button className="icon-button light" onClick={() => setVisible(!visible)} aria-label="Toggle balance visibility">
              {visible ? <Eye /> : <EyeOff />}
            </button>
            <div className="balance-line" />
          </section>

          <div className="dash-grid">
            <div>
              <div className="dash-section-head"><h2>Account overview</h2><button className="text-link">This month</button></div>
              <div className="stat-grid">
                <StatCard label="Available balance" value={visible ? "$0.00" : "••••••"} detail="No funds available yet" />
                <StatCard label="Investment profit" value={visible ? "$0.00" : "••••••"} detail="No profit recorded yet" />
                <StatCard label="Locked balance" value={visible ? "$0.00" : "••••••"} detail="No active positions" />
                <StatCard label="Next payout" value="-" detail="No payout scheduled" />
              </div>

              <div className="allocation">
                <div className="dash-section-head"><h2>Portfolio allocation</h2><button className="text-link">Details</button></div>
                <div className="allocation-body">
                  <div className="donut" />
                  <div className="legend">
                    <span>No portfolio allocation yet</span>
                  </div>
                </div>
              </div>
            </div>

            <div id="activity" className="activity">
              <div className="dash-section-head"><h2>Recent activity</h2><button className="text-link">View all</button></div>
              <p className="dashboard-empty-state">No activity yet. Your deposits, investments, and payouts will appear here.</p>
              <button className="button full-button">Open activity</button>
            </div>
          </div>
          </>}
        </main>
        {activeSection === "Overview" && <TradingViewMarketBoard theme={theme} />}
      </div>

      <nav className="mobile-dashboard-nav" aria-label="Mobile dashboard navigation">
        <button type="button" onClick={() => openMobileSection("Profit history")}><History size={18} /><span>History</span></button>
        <button type="button" onClick={() => openMobileSection("Deposit")}><Wallet size={18} /><span>Deposit</span></button>
        <button type="button" className="mobile-dashboard-home" onClick={() => openMobileSection("Overview")} aria-label="Dashboard home"><Home size={20} /></button>
        <button type="button" onClick={() => openMobileSection("Withdraw")}><ArrowDownToLine size={18} /><span>Withdraw</span></button>
        <button type="button" onClick={toggleMobileMenu} aria-label={sidebar ? "Close dashboard menu" : "Open dashboard menu"}><Menu size={19} /><span>Menu</span></button>
      </nav>
    </div>
  );
}
