"use client";

import { createContext, useContext, useEffect, useSyncExternalStore } from "react";

const translations = {
  en: { dashboard: "Dashboard", customers: "Customers", kyc: "KYC management", transactions: "Transactions", investments: "Investments", userFunds: "Manage User Funds", expertTraders: "Manage Expert Traders", swaps: "Swap activity", managedAccounts: "Managed accounts", deposits: "Deposits", withdrawals: "Withdrawals", investmentPlans: "Investment plans", profitHistory: "Profit history", profiles: "Profiles", referrals: "Referrals", support: "Support", paymentSettings: "Payment details", withdrawalSettings: "Withdrawal methods", manageSchema: "Manage Schema", schedule: "Schedule", holiday: "Holiday", editInvestmentPlans: "Edit Investment Plans", staff: "Staff management", settings: "Settings", welcome: "Welcome back. Here is what is happening with your platform today.", home: "Home", about: "About", contact: "Contact", login: "Login", signUp: "Sign Up", aboutUs: "About Us", contactUs: "Contact Us", companyInfo: "Company Info", language: "Language", contactEyebrow: "We're Here For You", getIn: "Get In", touch: "Touch", contactLead: "Have questions or need assistance? Our team is available 24/7 to help you." },
  es: { dashboard: "Panel", customers: "Clientes", kyc: "Gestión KYC", transactions: "Transacciones", investments: "Inversiones", userFunds: "Gestionar fondos de usuarios", expertTraders: "Gestionar traders expertos", manageSchema: "Gestionar esquema", schedule: "Programación", holiday: "Festivo", editInvestmentPlans: "Editar planes de inversión", staff: "Gestión de personal", settings: "Configuración", welcome: "Bienvenido. Esto es lo que sucede hoy en tu plataforma.", home: "Inicio", about: "Acerca de", contact: "Contacto", login: "Iniciar sesión", signUp: "Registrarse", aboutUs: "Sobre nosotros", contactUs: "Contáctanos", companyInfo: "Información de la empresa", language: "Idioma", contactEyebrow: "Estamos aquí para ayudarte", getIn: "Ponte en", touch: "Contacto", contactLead: "¿Tienes preguntas? Nuestro equipo está disponible 24/7 para ayudarte." },
  fr: { dashboard: "Tableau de bord", customers: "Clients", kyc: "Gestion KYC", transactions: "Transactions", investments: "Investissements", userFunds: "Gérer les fonds utilisateurs", expertTraders: "Gérer les traders experts", manageSchema: "Gérer le schéma", schedule: "Planning", holiday: "Jour férié", editInvestmentPlans: "Modifier les plans d'investissement", staff: "Gestion du personnel", settings: "Paramètres", welcome: "Bienvenue. Voici ce qui se passe sur votre plateforme aujourd'hui.", home: "Accueil", about: "À propos", contact: "Contact", login: "Connexion", signUp: "S'inscrire", aboutUs: "À propos de nous", contactUs: "Nous contacter", companyInfo: "Informations sur l'entreprise", language: "Langue", contactEyebrow: "Nous sommes là pour vous", getIn: "Prenez", touch: "Contact", contactLead: "Des questions ? Notre équipe est disponible 24h/24 et 7j/7 pour vous aider." },
  de: { dashboard: "Dashboard", customers: "Kunden", kyc: "KYC-Verwaltung", transactions: "Transaktionen", investments: "Investitionen", userFunds: "Benutzerfonds verwalten", expertTraders: "Expertenhändler verwalten", manageSchema: "Schema verwalten", schedule: "Zeitplan", holiday: "Feiertag", editInvestmentPlans: "Anlagepläne bearbeiten", staff: "Mitarbeiter", settings: "Einstellungen", welcome: "Willkommen zurück. Das passiert heute auf Ihrer Plattform.", home: "Startseite", about: "Über uns", contact: "Kontakt", login: "Anmelden", signUp: "Registrieren", aboutUs: "Über uns", contactUs: "Kontaktieren Sie uns", companyInfo: "Unternehmensinfo", language: "Sprache", contactEyebrow: "Wir sind für Sie da", getIn: "Kontakt", touch: "aufnehmen", contactLead: "Fragen? Unser Team ist rund um die Uhr für Sie da." },
  pt: { dashboard: "Painel", customers: "Clientes", kyc: "Gestão KYC", transactions: "Transações", investments: "Investimentos", userFunds: "Gerenciar fundos do usuário", expertTraders: "Gerenciar traders especialistas", manageSchema: "Gerenciar esquema", schedule: "Cronograma", holiday: "Feriado", editInvestmentPlans: "Editar planos de investimento", staff: "Equipe", settings: "Configurações", welcome: "Bem-vindo. Veja o que acontece hoje na sua plataforma.", home: "Início", about: "Sobre", contact: "Contato", login: "Entrar", signUp: "Cadastrar", aboutUs: "Sobre nós", contactUs: "Fale conosco", companyInfo: "Informações da empresa", language: "Idioma", contactEyebrow: "Estamos aqui para você", getIn: "Entre em", touch: "contato", contactLead: "Tem dúvidas? Nossa equipe está disponível 24 horas por dia." },
  ja: { dashboard: "ダッシュボード", customers: "顧客", kyc: "KYC管理", transactions: "取引", investments: "投資", userFunds: "ユーザー資金を管理", expertTraders: "専門トレーダーを管理", manageSchema: "スキーマ管理", schedule: "スケジュール", holiday: "休日", editInvestmentPlans: "投資プランを編集", staff: "スタッフ", settings: "設定", welcome: "おかえりなさい。今日のプラットフォーム情報です。", home: "ホーム", about: "概要", contact: "お問い合わせ", login: "ログイン", signUp: "登録", aboutUs: "私たちについて", contactUs: "お問い合わせ", companyInfo: "会社情報", language: "言語", contactEyebrow: "あなたのために", getIn: "お問い合わせ", touch: "ください", contactLead: "ご質問がありますか？チームが24時間対応します。" },
  zh: { dashboard: "仪表盘", customers: "客户", kyc: "KYC管理", transactions: "交易", investments: "投资", userFunds: "管理用户资金", expertTraders: "管理专家交易员", manageSchema: "管理模式", schedule: "日程", holiday: "假期", editInvestmentPlans: "编辑投资计划", staff: "员工", settings: "设置", welcome: "欢迎回来。这是平台今天的动态。", home: "首页", about: "关于", contact: "联系", login: "登录", signUp: "注册", aboutUs: "关于我们", contactUs: "联系我们", companyInfo: "公司信息", language: "语言", contactEyebrow: "我们随时为您服务", getIn: "联系我们", touch: "", contactLead: "有问题吗？我们的团队全天候为您提供帮助。" },
};

const interfaceTranslations = {
  en: { notifications: "Notifications", markAllRead: "Clear all", noNotifications: "No new notifications" },
  es: { notifications: "Notificaciones", markAllRead: "Borrar todas", noNotifications: "No hay notificaciones nuevas" },
  fr: { notifications: "Notifications", markAllRead: "Tout effacer", noNotifications: "Aucune nouvelle notification" },
  de: { notifications: "Benachrichtigungen", markAllRead: "Alle löschen", noNotifications: "Keine neuen Benachrichtigungen" },
  pt: { notifications: "Notificações", markAllRead: "Limpar tudo", noNotifications: "Nenhuma notificação nova" },
  ja: { notifications: "通知", markAllRead: "すべて消去", noNotifications: "新しい通知はありません" },
  zh: { notifications: "通知", markAllRead: "清除全部", noNotifications: "没有新通知" },
};

const landingTranslations = {
  en: { secureMarkets: "Since 2011 · Secure markets", heroTitle: "Become a better investor on the go.", heroLead: "Follow markets live, understand momentum, and move from signal to decision without the noise.", getStarted: "Get started", exploreMarkets: "Explore every market", liveData: "Live data", liveAnalysis: "Live analysis", bitcoinCalculator: "Bitcoin calculator", calculatorLead: "Find out the current Bitcoin value with our easy-to-use converter.", clientStories: "CLIENT STORIES", trustedPeople: "Trusted by people moving forward", builtForNext: "Built for the next move", clearView: "One clear view of a world in motion.", openDashboard: "Open your dashboard" },
  es: { secureMarkets: "Desde 2011 · Mercados seguros", heroTitle: "Conviértete en un mejor inversor estés donde estés.", heroLead: "Sigue los mercados en vivo, entiende el impulso y pasa de la señal a la decisión sin ruido.", getStarted: "Comenzar", exploreMarkets: "Explora todos los mercados", liveData: "Datos en vivo", liveAnalysis: "Análisis en vivo", bitcoinCalculator: "Calculadora de Bitcoin", calculatorLead: "Descubre el valor actual de Bitcoin con nuestro conversor fácil de usar.", clientStories: "HISTORIAS DE CLIENTES", trustedPeople: "Personas que avanzan con confianza", builtForNext: "Creado para tu próximo movimiento", clearView: "Una visión clara de un mundo en movimiento.", openDashboard: "Abrir tu panel" },
  fr: { secureMarkets: "Depuis 2011 · Marchés sécurisés", heroTitle: "Devenez un meilleur investisseur, où que vous soyez.", heroLead: "Suivez les marchés en direct, comprenez la dynamique et passez du signal à la décision sans bruit.", getStarted: "Commencer", exploreMarkets: "Explorer tous les marchés", liveData: "Données en direct", liveAnalysis: "Analyse en direct", bitcoinCalculator: "Calculateur Bitcoin", calculatorLead: "Découvrez la valeur actuelle du Bitcoin avec notre convertisseur simple.", clientStories: "TÉMOIGNAGES CLIENTS", trustedPeople: "La confiance de ceux qui avancent", builtForNext: "Conçu pour votre prochain mouvement", clearView: "Une vision claire d’un monde en mouvement.", openDashboard: "Ouvrir votre tableau de bord" },
  de: { secureMarkets: "Seit 2011 · Sichere Märkte", heroTitle: "Werden Sie unterwegs ein besserer Anleger.", heroLead: "Verfolgen Sie Märkte live, verstehen Sie die Dynamik und treffen Sie klare Entscheidungen.", getStarted: "Loslegen", exploreMarkets: "Alle Märkte entdecken", liveData: "Live-Daten", liveAnalysis: "Live-Analyse", bitcoinCalculator: "Bitcoin-Rechner", calculatorLead: "Ermitteln Sie den aktuellen Bitcoin-Wert mit unserem einfachen Konverter.", clientStories: "KUNDENGESCHICHTEN", trustedPeople: "Vertrauen von Menschen, die vorankommen", builtForNext: "Für den nächsten Schritt entwickelt", clearView: "Ein klarer Blick auf eine Welt in Bewegung.", openDashboard: "Dashboard öffnen" },
  pt: { secureMarkets: "Desde 2011 · Mercados seguros", heroTitle: "Torne-se um investidor melhor em qualquer lugar.", heroLead: "Acompanhe os mercados ao vivo, entenda o movimento e transforme sinais em decisões.", getStarted: "Começar", exploreMarkets: "Explorar todos os mercados", liveData: "Dados ao vivo", liveAnalysis: "Análise ao vivo", bitcoinCalculator: "Calculadora de Bitcoin", calculatorLead: "Veja o valor atual do Bitcoin com nosso conversor fácil de usar.", clientStories: "HISTÓRIAS DE CLIENTES", trustedPeople: "A confiança de quem segue em frente", builtForNext: "Feito para seu próximo movimento", clearView: "Uma visão clara de um mundo em movimento.", openDashboard: "Abrir seu painel" },
  ja: { secureMarkets: "2011年創業 · 安心のマーケット", heroTitle: "いつでも、より良い投資家へ。", heroLead: "市場をリアルタイムで追い、流れを理解し、迷いなく判断しましょう。", getStarted: "始める", exploreMarkets: "すべての市場を見る", liveData: "ライブデータ", liveAnalysis: "ライブ分析", bitcoinCalculator: "ビットコイン計算機", calculatorLead: "使いやすいコンバーターで現在のビットコイン価格を確認できます。", clientStories: "お客様の声", trustedPeople: "前進する人々に選ばれています", builtForNext: "次の一歩のために", clearView: "動き続ける世界を、ひとつの明確な画面で。", openDashboard: "ダッシュボードを開く" },
  zh: { secureMarkets: "始于2011 · 安全市场", heroTitle: "随时随地，成为更好的投资者。", heroLead: "实时关注市场，理解趋势，从信号到决策不再被噪音干扰。", getStarted: "开始使用", exploreMarkets: "探索所有市场", liveData: "实时数据", liveAnalysis: "实时分析", bitcoinCalculator: "比特币计算器", calculatorLead: "使用简单易用的转换器查看当前比特币价值。", clientStories: "客户故事", trustedPeople: "值得每一位前行者信赖", builtForNext: "为下一步而生", clearView: "清晰看见不断变化的世界。", openDashboard: "打开仪表盘" },
};

const landingSectionTranslations = {
  en: { total24hVolume: "Total 24h volume", totalMarketCap: "Total market cap", connectingMarkets: "Connecting to markets...", bitcoinAmount: "Bitcoin amount", displayCurrency: "Display currency", updatedFromLive: "Data updated from live market pricing", secureTransactions: "Secure & Fast Transactions", openAccount: "Open an account for free and start investing with confidence.", product: "Product", markets: "Markets", company: "Company", aboutUsFooter: "About us", supportFooter: "Support", careersFooter: "Careers", legal: "Legal & Regulatory", terms: "Terms & Conditions", disclosuresFooter: "Disclosures", lawRequests: "Law Enforcement Requests", followUs: "Follow us on", brokerage: "Brokerage services", portfolio: "Portfolio Management", futures: "Futures and cleared trading" },
  es: { total24hVolume: "Volumen total de 24 h", totalMarketCap: "Capitalización total del mercado", connectingMarkets: "Conectando con los mercados...", bitcoinAmount: "Cantidad de Bitcoin", displayCurrency: "Moneda de visualización", updatedFromLive: "Datos actualizados del mercado en vivo", secureTransactions: "Transacciones seguras y rápidas", openAccount: "Abre una cuenta gratis y empieza a invertir con confianza.", product: "Producto", markets: "Mercados", company: "Empresa", aboutUsFooter: "Sobre nosotros", supportFooter: "Soporte", careersFooter: "Empleo", legal: "Legal y regulación", terms: "Términos y condiciones", disclosuresFooter: "Divulgaciones", lawRequests: "Solicitudes de las autoridades", followUs: "Síguenos en", brokerage: "Servicios de corretaje", portfolio: "Gestión de carteras", futures: "Futuros y operaciones compensadas" },
  fr: { total24hVolume: "Volume total sur 24 h", totalMarketCap: "Capitalisation totale du marché", connectingMarkets: "Connexion aux marchés...", bitcoinAmount: "Montant de Bitcoin", displayCurrency: "Devise d’affichage", updatedFromLive: "Données mises à jour depuis le marché en direct", secureTransactions: "Transactions sûres et rapides", openAccount: "Ouvrez un compte gratuitement et investissez en toute confiance.", product: "Produit", markets: "Marchés", company: "Entreprise", aboutUsFooter: "À propos de nous", supportFooter: "Assistance", careersFooter: "Carrières", legal: "Juridique et réglementation", terms: "Conditions générales", disclosuresFooter: "Informations réglementaires", lawRequests: "Demandes des autorités", followUs: "Suivez-nous sur", brokerage: "Services de courtage", portfolio: "Gestion de portefeuille", futures: "Contrats à terme et compensation" },
  de: { total24hVolume: "Gesamtvolumen 24 Std.", totalMarketCap: "Gesamte Marktkapitalisierung", connectingMarkets: "Märkte werden verbunden...", bitcoinAmount: "Bitcoin-Betrag", displayCurrency: "Anzeigewährung", updatedFromLive: "Daten aus dem Live-Markt aktualisiert", secureTransactions: "Sichere und schnelle Transaktionen", openAccount: "Eröffnen Sie kostenlos ein Konto und investieren Sie mit Vertrauen.", product: "Produkt", markets: "Märkte", company: "Unternehmen", aboutUsFooter: "Über uns", supportFooter: "Support", careersFooter: "Karriere", legal: "Recht und Regulierung", terms: "Geschäftsbedingungen", disclosuresFooter: "Offenlegungen", lawRequests: "Anfragen von Strafverfolgungsbehörden", followUs: "Folgen Sie uns auf", brokerage: "Maklerdienste", portfolio: "Portfoliomanagement", futures: "Futures und Clearing" },
  pt: { total24hVolume: "Volume total em 24h", totalMarketCap: "Capitalização total do mercado", connectingMarkets: "Conectando aos mercados...", bitcoinAmount: "Quantidade de Bitcoin", displayCurrency: "Moeda de exibição", updatedFromLive: "Dados atualizados do mercado ao vivo", secureTransactions: "Transações seguras e rápidas", openAccount: "Abra uma conta grátis e comece a investir com confiança.", product: "Produto", markets: "Mercados", company: "Empresa", aboutUsFooter: "Sobre nós", supportFooter: "Suporte", careersFooter: "Carreiras", legal: "Legal e regulamentação", terms: "Termos e condições", disclosuresFooter: "Divulgações", lawRequests: "Solicitações das autoridades", followUs: "Siga-nos em", brokerage: "Serviços de corretagem", portfolio: "Gestão de portfólio", futures: "Futuros e negociação compensada" },
  ja: { total24hVolume: "24時間総取引量", totalMarketCap: "時価総額", connectingMarkets: "市場に接続しています...", bitcoinAmount: "ビットコイン数量", displayCurrency: "表示通貨", updatedFromLive: "ライブ市場のデータを更新しました", secureTransactions: "安全で高速な取引", openAccount: "無料で口座を開設し、自信を持って投資を始めましょう。", product: "プロダクト", markets: "市場", company: "会社", aboutUsFooter: "私たちについて", supportFooter: "サポート", careersFooter: "採用情報", legal: "法務・規制", terms: "利用規約", disclosuresFooter: "開示情報", lawRequests: "法執行機関からの依頼", followUs: "フォロー", brokerage: "仲介サービス", portfolio: "ポートフォリオ管理", futures: "先物・清算取引" },
  zh: { total24hVolume: "24小时总交易量", totalMarketCap: "总市值", connectingMarkets: "正在连接市场...", bitcoinAmount: "比特币数量", displayCurrency: "显示货币", updatedFromLive: "实时市场数据已更新", secureTransactions: "安全快速的交易", openAccount: "免费开户，充满信心地开始投资。", product: "产品", markets: "市场", company: "公司", aboutUsFooter: "关于我们", supportFooter: "支持", careersFooter: "招聘", legal: "法律与监管", terms: "条款与条件", disclosuresFooter: "披露信息", lawRequests: "执法请求", followUs: "关注我们", brokerage: "经纪服务", portfolio: "投资组合管理", futures: "期货及清算交易" },
};

const LanguageContext = createContext({ language: "en", setLanguage: () => {}, t: key => translations.en[key] || key });

function subscribeToLanguage(onChange) {
  window.addEventListener("storage", onChange);
  window.addEventListener("rivertrade-language-change", onChange);
  return () => {
    window.removeEventListener("storage", onChange);
    window.removeEventListener("rivertrade-language-change", onChange);
  };
}

function getLanguageSnapshot() {
  const savedLanguage = localStorage.getItem("rivertrade-language");
  return savedLanguage && translations[savedLanguage] ? savedLanguage : "en";
}

function getServerLanguageSnapshot() {
  return "en";
}

export function LanguageProvider({ children }) {
  const language = useSyncExternalStore(subscribeToLanguage, getLanguageSnapshot, getServerLanguageSnapshot);
  const changeLanguage = value => {
    if (!translations[value]) return;
    localStorage.setItem("rivertrade-language", value);
    window.dispatchEvent(new Event("rivertrade-language-change"));
  };
  const t = key => translations[language]?.[key] || interfaceTranslations[language]?.[key] || landingTranslations[language]?.[key] || landingSectionTranslations[language]?.[key] || translations.en[key] || interfaceTranslations.en[key] || landingTranslations.en[key] || landingSectionTranslations.en[key] || key;
  useEffect(() => { document.documentElement.lang = language; }, [language]);
  return <LanguageContext.Provider value={{ language, setLanguage: changeLanguage, t }}>{children}</LanguageContext.Provider>;
}
export const useLanguage = () => useContext(LanguageContext);
